FAQ Application
Ayushparikh-code/Web-dev-mini-projects pull request #136
Opened 2021-07-07 04:50 UTC by khushi-purwar

I have added the FAQ Accordion. Please check my PR @Ayushparikh-code 

<img width="960" alt="ss1" src="https://user-images.githubusercontent.com/52875298/124701874-f486ab00-df0c-11eb-944e-9053479a7e13.png">

2021-07-07 08:48 UTC, Ayushparikh-code requested changes
screenshot not showing

2021-07-07 08:48 UTC, Ayushparikh-code commented on FAQ Application/README.md
> +
add screenshot here

2021-07-07 10:13 UTC, khushi-purwar commented on FAQ Application/README.md
> +
done!

2021-07-07 11:10 UTC, chicken-biryani reviewed
Also add your project link and description to index.md

2021-07-07 11:10 UTC, chicken-biryani commented on FAQ Application/style.css
> +
Add a new line

2021-07-07 11:10 UTC, chicken-biryani commented on FAQ Application/README.md
> +
The description is blank. Also, add a "Use of this project" section and describe where can this project be used.

2021-07-08 08:17 UTC, Ayushparikh-code approved these changes
LGTM

2021-07-08 08:18 UTC, merged