Battery Indicator
Ayushparikh-code/Web-dev-mini-projects pull request #160
Opened 2021-07-08 20:26 UTC by Jagannath8

This is a battery indicator app which is used to know battery percentage of the system.

2021-07-09 08:31 UTC, Ayushparikh-code approved these changes

2021-07-09 17:19 UTC, chicken-biryani reviewed
Everything looks pretty good in my opinion. Just add your project name and link in index.md. and do the additions/changes as requested.

2021-07-09 17:19 UTC, chicken-biryani commented on Battery Indicator/style.css
> +}
Add a new line at the end of file.

2021-07-09 17:19 UTC, chicken-biryani commented on Battery Indicator/script.js
> +});
Add a new line at the end of file.

2021-07-09 17:19 UTC, chicken-biryani commented on Battery Indicator/index.html
> +</html>
Add a new line at the end of file.

2021-07-09 17:19 UTC, chicken-biryani commented on Battery Indicator/README.md
> +![battery-indicator](https://github.com/Jagannath8/Web-dev-mini-projects/blob/battery/Battery%20Indicator/dark.jpg)
Move images to the end. And add Output // Screenshots as a header.

2021-07-09 17:22 UTC, chicken-biryani reviewed
Also add a steps to set up project. Use PR #159 's README as a reference

2021-07-09 18:48 UTC, harshita2216 requested changes
Please add this in index.md, as requested by @chicken-biryani. Then we are good to go! 🚀

2021-07-09 18:57 UTC, Jagannath8 commented
what link I had to provide? @harshita2216 
![image](https://user-images.githubusercontent.com/64650848/125124347-8d881280-e115-11eb-876e-a7813dac944f.png)

2021-07-09 19:15 UTC, harshita2216 commented on Index.md
> +| Score Keeper                                                                                                                  |A web Page where user can keep a count of their scores and will tell w
Link of Score Keeper? 
Also, why did you create a new file?

2021-07-09 19:16 UTC, Jagannath8 commented
Can I make a fresh pr?

2021-07-09 19:20 UTC, harshita2216 commented
> Can I make a fresh pr?

@Jagannath8, sure you may. Please take your time. You need not hurry.

2021-07-10 05:11 UTC, chicken-biryani commented
@Jagannath8 can i close this one?

2021-07-10 06:27 UTC, Jagannath8 commented
yess @chicken-biryani

2021-07-10 06:39 UTC, closed without merging