Added JS tip calc
Ayushparikh-code/Web-dev-mini-projects pull request #161
Opened 2021-07-08 20:27 UTC by supzi-del

Fixes #156

2021-07-08 21:08 UTC, chicken-biryani reviewed
1)Add project name in form of link and description in index.md
2) Contents of the README:

-Project overview.
-Use of the project.
-Stack of your project.
-How to set up / run your project.
-Screenshots of the pages/output.
(A short description under each screenshot... Describing the page a little bit)
This would help visitors/developers in general

3)Please use the following tools to increase the readability of your README / Scripts before creating a pull request.
It is a good practice.

Markdown - https://codebeautify.org/markdown-formatter
HTML - https://codebeautify.org/htmlviewer
CSS - https://codebeautify.org/css-beautify-minify
JS - https://codebeautify.org/jsviewer

Use this PR as a reference :
#93

2021-07-08 21:08 UTC, chicken-biryani commented on Tip Calculator/styles.css
> +  }
Add a new line at the end of file. Use a CSS beautifier.

2021-07-08 21:08 UTC, chicken-biryani commented on Tip Calculator/script.js
> +  }
Add a new line at the end of file.

Use a JS beautifier.

2021-07-08 21:08 UTC, chicken-biryani commented on Tip Calculator/index.html
> +</html>
Add a new line at the end of the file. 
Use an HTML beautifier.

2021-07-09 08:30 UTC, Ayushparikh-code approved these changes

2021-07-12 13:22 UTC, Ayushparikh-code requested changes
Add project name in form of link and description in index.md

2021-07-12 19:56 UTC, supzi-del commented
Hey, what can I do about the conflicts?

2021-07-13 05:56 UTC, harshita2216 reviewed
I've resolved the conflicts.

2021-07-13 05:56 UTC, merged

2021-09-30 08:08 UTC, supzi-del commented
Hey, can you please add the LGMSOC21 label so that this PR can be counted for the program?