Added online quiz portal #122
Ayushparikh-code/Web-dev-mini-projects pull request #167
Opened 2021-07-09 19:33 UTC by jyothi-k-g

2021-07-10 05:11 UTC, Ayushparikh-code approved these changes

2021-07-10 12:04 UTC, chicken-biryani reviewed
Add project name in form of link and description in index.md
Please use the following tools to increase the readability of your README / Scripts before creating a pull request.
It is a good practice.

Markdown - https://codebeautify.org/markdown-formatter
HTML - https://codebeautify.org/htmlviewer
CSS - https://codebeautify.org/css-beautify-minify
JS - https://codebeautify.org/jsviewer
Use this PR as a reference :
#93

2021-07-10 12:04 UTC, chicken-biryani commented on online quiz portal/style.css
> +}
Add a new line at the end of file.

Use a css beautifier.

2021-07-10 12:04 UTC, chicken-biryani commented on online quiz portal/script.js
> +}
Add a new line at the end of file.

Use a js beautifier.

2021-07-10 12:04 UTC, chicken-biryani commented on online quiz portal/question.js
> +];
Add a new line at the end of file.

Use a js beautifier.

2021-07-13 07:45 UTC, jyothi-k-g commented
@chicken-biryani  I have done all the required changes which was mentioned could you please review it

2021-07-13 08:38 UTC, harshita2216 requested changes
Add your details to the index.md file. @jyothi-k-g

2021-07-13 08:50 UTC, jyothi-k-g commented
@harshita2216  What are the details that should be added in index.md file?

2021-07-13 11:00 UTC, harshita2216 commented
> @harshita2216 What are the details that should be added in index.md file?

Please see the index.md file. 
Name, Link and a small description, the way others have done.

2021-07-13 16:59 UTC, jyothi-k-g commented
> > @harshita2216 What are the details that should be added in index.md file?
> 
> Please see the index.md file.
> Name, Link and a small description, the way others have done.

I have included the details but as for the link should I include the link of my repository?

2021-07-13 17:09 UTC, harshita2216 commented
> > > @harshita2216 What are the details that should be added in index.md file?
> > 
> > 
> > Please see the index.md file.
> > Name, Link and a small description, the way others have done.
> 
> I have included the details but as for the link should I include the link of my repository?

Refer to the index.md file and the details that others have put.

2021-07-13 17:12 UTC, jyothi-k-g commented
> > > > @harshita2216 What are the details that should be added in index.md file?
> > > 
> > > 
> > > Please see the index.md file.
> > > Name, Link and a small description, the way others have done.
> > 
> > 
> > I have included the details but as for the link should I include the link of my repository?
> 
> Refer to the index.md file and the details that others have put.

Others have included the links of main open source repository which include their project in that.

2021-07-13 17:14 UTC, jyothi-k-g commented
I can only copy the link from my own repository which include the project and paste it in index.md file

2021-07-13 17:19 UTC, merged