Button change effect app
Ayushparikh-code/Web-dev-mini-projects pull request #168
Opened 2021-07-10 02:18 UTC by RiyaGupta89

Added the buttons color changing effect project in the repository. 
![challenge1](https://user-images.githubusercontent.com/72425181/125148896-20936d80-e153-11eb-8c3f-4a7e12e9ad58.png)
![challenge2](https://user-images.githubusercontent.com/72425181/125148898-225d3100-e153-11eb-8b06-3ecd1e765409.png)

2021-07-10 02:31 UTC, harshita2216 commented
@RiyaGupta89, please update the description and mention the issue number. Thanks.

2021-07-10 02:44 UTC, RiyaGupta89 commented
@harshita2216  Done. I edited my message. Please have a look.

2021-07-10 03:03 UTC, harshita2216 requested changes
Please update index.md and add a readme. @RiyaGupta89

2021-07-10 03:08 UTC, RiyaGupta89 commented
@harshita2216 Where is index.md?

2021-07-10 03:33 UTC, RiyaGupta89 commented
![dir](https://user-images.githubusercontent.com/72425181/125150469-a4525780-e15d-11eb-9005-84b8662727ac.png)
Can't find index.md, which command should i run?

2021-07-10 14:14 UTC, Ayushparikh-code commented
> ![dir](https://user-images.githubusercontent.com/72425181/125150469-a4525780-e15d-11eb-9005-84b8662727ac.png)
> Can't find index.md, which command should i run?

@RiyaGupta89  do again fetch the upstream of original repo & merge it to ur cloned repo then check again hope u will find that folder ...

2021-07-12 06:14 UTC, RiyaGupta89 commented
@Ayushparikh-code  @harshita2216  Added the project in index.md also added a readme file. Please review my PR.

2021-07-13 05:10 UTC, RiyaGupta89 commented
How can I resolve the issue? Please help.

2021-07-13 05:13 UTC, harshita2216 commented on JAVASCRIPT BUTTON APP/README.md
> +![Demo2](public/images/challenge2.png)
Image doesn't show. Please check?

2021-07-13 05:14 UTC, harshita2216 commented on JAVASCRIPT BUTTON APP/README.md
> +![Demo2](public/images/challenge2.png)
Also the screenshots doesn't follow markdown. Check the preview please?

2021-07-13 05:15 UTC, harshita2216 commented
@RiyaGupta89, update your fork please. Then add your project in the index.md file.

2021-07-13 05:20 UTC, harshita2216 commented
@RiyaGupta89, I have resolved the conflicts. Please check the image only then we'll merge it.

2021-07-13 05:22 UTC, RiyaGupta89 commented
![image](https://user-images.githubusercontent.com/72425181/125395097-59884800-e3c8-11eb-962c-d5ad8f635a4a.png)
I can see my images here, i don't know why its not visible there. I did the same in survey form website,  there it worked completely fine.

2021-07-13 05:34 UTC, RiyaGupta89 commented
Or else merge this one, i will create a seperate issue for correcting images, if there are any problem with images.

2021-07-13 05:35 UTC, RiyaGupta89 commented
@harshita2216 Oh, okay. Thanks alot.

2021-07-13 05:38 UTC, harshita2216 approved these changes

2021-07-13 05:38 UTC, merged