Typing Speed Test Website
Ayushparikh-code/Web-dev-mini-projects pull request #177
Opened 2021-07-10 18:42 UTC by khushi-purwar

#157  Added Typing Speed Test Website. Please review my PR @chicken-biryani 

<img width="956" alt="ss1" src="https://user-images.githubusercontent.com/52875298/125173158-727fd600-e1db-11eb-9010-6a6cb75243ef.png">

2021-07-11 15:24 UTC, harshita2216 requested changes
Great work @khushi-purwar. Just add it to index.md and then we shall be good to go! 🚀

2021-07-11 17:40 UTC, chicken-biryani commented on Typing Speed Test Website/style.css
> +
Remove the extra line.

2021-07-11 17:40 UTC, chicken-biryani commented on Typing Speed Test Website/script.js
> +
Remove the extra lines

2021-07-11 17:40 UTC, chicken-biryani commented on Typing Speed Test Website/index.html
> +
Remove the extra line

2021-07-12 03:49 UTC, khushi-purwar commented
> Great work @khushi-purwar. Just add it to index.md and then we shall be good to go! 🚀

Added in the index.md

2021-07-12 09:23 UTC, merged