165 day of week app
Ayushparikh-code/Web-dev-mini-projects pull request #183
Opened 2021-07-11 14:00 UTC by sonamgupta136

## Week Day Predictor App

    A simple week  day predictor app using HTML , CSS and JAVASCRIPT.

## Use Of Project :

    This app displays the current day of the week with amazing quotes. 

## Technologies Used:
     - HTML
     - CSS
     - JAVASCRIPT

## Steps to Use:

---

 - Download or clone the repository

```
    "git clone https://github.com/Ayushparikh-code/Web-dev-mini-projects.git"
```

 - Go to the directory
 - Run the index.html file
 - Result is here!!!

## Screenshot:
![Screenshot (18)](https://user-images.githubusercontent.com/66966120/125198145-93651d00-e215-11eb-9604-28e2e416228e.png)

2021-07-11 15:10 UTC, Ayushparikh-code requested changes
hey @sonamgupta136 u added two same readme.md so delete any of the one , 
and do update and add your project name & description in Index.md file(https://github.com/Ayushparikh-code/Web-dev-mini-projects/blob/main/Index.md)

2021-07-11 17:34 UTC, chicken-biryani reviewed
@sonamgupta136 You've done really very well.

Can u just add a screenshot above the Demo and it's good to go! Excellent!

2021-07-12 11:24 UTC, sonamgupta136 commented
@chicken-biryani  #165 please review now.

2021-07-12 12:46 UTC, harshita2216 commented on Index.md
> -| [Battery Percentage Indicator](https://github.com/Ayushparikh-code/Web-dev-mini-projects/tree/main/Battery%20Indicator)      |This is a battery indicator app which is used to know battery percentag
Read my review in #189

2021-07-12 15:10 UTC, Ayushparikh-code approved these changes

2021-07-12 15:10 UTC, merged