Create Covid 19 Awarness Website
Ayushparikh-code/Web-dev-mini-projects pull request #194
Opened 2021-07-12 17:35 UTC by Sulagna-Dutta-Roy

### Description

(Describe your project over here.)

### Checklist

- [ ] I've been assigned an issue related to this PR.
- [ ] I've used beautifiers.
- [ ] I've added my Project's name and description to `Index.md`
- [ ] I've made a README.md file for my Project.
- [ ] The README.md file of my projrct contains Project title, Description, Use of project, Set up, Stack used and Output (Screenshots). 

## Related Issues or Pull Requests number

(Write your answer here.)

2021-07-12 18:40 UTC, chicken-biryani commented
@Sulagna-Dutta-Roy please edit the PR comment. Describe the project and use "#issue no." Refer to the issue it deals with.

2021-07-12 21:32 UTC, chicken-biryani commented
@Sulagna-Dutta-Roy please go through the changes you've done again.

You've changed the files you should not be changing.

Refer to this PR : 

https://github.com/Ayushparikh-code/Web-dev-mini-projects/pull/173

2021-07-13 04:32 UTC, harshita2216 requested changes
Also add your project details only in the index.md file.

2021-07-13 04:32 UTC, harshita2216 commented on README.md
> -
You've removed the readme of the repository. You have to create a readme for your own project. @Sulagna-Dutta-Roy

2021-07-13 04:38 UTC, Ayushparikh-code requested changes
Hey @Sulagna-Dutta-Roy you directly added your project files in the original repo, so do make a seperate folder for your project inside repo and then add all files in that folders ...

2021-07-13 11:17 UTC, harshita2216 commented
@Sulagna-Dutta-Roy, let me know when you're done making the changes.

2021-07-13 11:28 UTC, Sulagna-Dutta-Roy commented
I've done done changes. Please check it

2021-07-13 11:32 UTC, harshita2216 commented on README.md
> -
@Sulagna-Dutta-Roy, Don't remove this, please,

2021-07-13 11:38 UTC, harshita2216 commented
> I've done done changes. Please check it

Hi, you've deleted the entire readme of the repo. Please check and make the changes. Thanks!

2021-07-13 11:52 UTC, Sulagna-Dutta-Roy commented
I've added the readme.md .Please check

2021-07-15 15:55 UTC, merged