Word counter #135
Ayushparikh-code/Web-dev-mini-projects pull request #199
Opened 2021-07-13 06:30 UTC by kshitija-2001

### Description

Word counter app 

### Checklist

- [ ] I've been assigned an issue related to this PR.
- [ ] I've used beautifiers.
- [ ] I've added my Project's name and description to `Index.md`
- [ ] I've made a README.md file for my Project.
- [ ] The README.md file of my project contains Project title, Description, Use of project, Set up, Stack used and Output (Screenshots). 

## Related Issues or Pull Requests number

(Write your answer here.)

2021-07-13 08:35 UTC, harshita2216 requested changes
Add your project to index.md file as well.

2021-07-13 08:35 UTC, harshita2216 commented on word counter/readme.md
> +
@kshitija-2001, please elaborate the steps.

2021-07-13 08:35 UTC, harshita2216 commented on word counter/readme.md
> +
@kshitija-2001, please elaborate the steps.

2021-07-13 09:01 UTC, kshitija-2001 commented
corrected the requested changes

2021-07-14 02:39 UTC, harshita2216 requested changes
Everything else looks fine!

2021-07-14 02:39 UTC, harshita2216 commented on word counter/readme.md
> +
Screenshots? @kshitija-2001

2021-07-14 04:28 UTC, kshitija-2001 commented on word counter/readme.md
> +
done added one screenshot

2021-07-14 04:32 UTC, harshita2216 approved these changes

2021-07-14 07:44 UTC, merged