added password_generator app
Ayushparikh-code/Web-dev-mini-projects pull request #213
Opened 2021-07-14 15:45 UTC by nagasaisriya

### Description
Password generator app
(Describe your project over here.)

### Checklist

- [x] I've been assigned an issue related to this PR.
- [x] I've used beautifiers.
- [ ] I've added my Project's name and description to `Index.md`
- [x] I've made a README.md file for my Project.
- [x] The README.md file of my projrct contains Project title, Description, Use of project, Set up, Stack used and Output (Screenshots). 

## Related Issues or Pull Requests number
Fixes #212 
(Write your answer here.)

2021-07-15 08:45 UTC, harshita2216 requested changes
Please add your project details to the index.md file.

2021-07-16 09:13 UTC, nagasaisriya commented
@harshita2216 added the project to inex.html file, please review it and let me know if any further changes are needed:)

2021-07-16 10:54 UTC, chicken-biryani commented on Password Generator/index.html
> +</html>
Add a new line at the eof.

2021-07-16 10:54 UTC, chicken-biryani commented on Password Generator/script.js
> +}
Add a new line at the eof.

2021-07-16 10:54 UTC, chicken-biryani commented on Password Generator/style.css
> +}
Add a new line at the eof.

2021-07-16 11:08 UTC, nagasaisriya commented on Password Generator/index.html
> +</html>
added newlines to eof

2021-07-16 11:13 UTC, harshita2216 approved these changes

2021-07-16 11:13 UTC, merged