readme file added to the band website.
Ayushparikh-code/Web-dev-mini-projects pull request #237
Opened 2021-07-17 03:58 UTC by jugeshraghav

### Description

It is a multi pager Band Website with simple but user-friendly design.

### Checklist

- [ ] I've been assigned an issue related to this PR.
- [ ] I've used beautifiers.
- [ ] I've added my Project's name and description to `Index.md`
- [ ] I've made a README.md file for my Project.
- [ ] The README.md file of my project contains Project title, Description, Use of project, Set up, Stack used and Output (Screenshots). 

## Related Issues or Pull Requests number

#140

2021-07-17 03:59 UTC, jugeshraghav commented
hey @chicken-biryani  @harshita2216 i have added the website please have a look

2021-07-17 04:02 UTC, jugeshraghav commented
everything up to date.

2021-07-17 10:19 UTC, Ayushparikh-code requested changes

2021-07-17 10:19 UTC, Ayushparikh-code commented on Index.md
> +| [Band website](https://github.com/Ayushparikh-code/Web-dev-mini-projects/tree/main/Band Website)              |A Band website with a simple and user friendly design and multiple pages with some ext
correct it and update properly!

2021-07-18 08:17 UTC, harshita2216 requested changes
Hey, the images in the readme file aren't working I think and the link of your project is wrongly written in the index.md file. Instead of space, %20 should be written.
Please make the above changes. Thanks!

2021-07-18 08:37 UTC, jugeshraghav commented
i have corrected the name of the website in the index,md and the images are visible in the readme at my end please check again.
![Screenshot (132)](https://user-images.githubusercontent.com/74092377/126061101-6273731c-20ea-45ae-81ee-2dfed3d1af7d.png)

2021-07-18 08:42 UTC, harshita2216 approved these changes

2021-07-18 08:43 UTC, merged