Text to speech converter
Ayushparikh-code/Web-dev-mini-projects pull request #257
Opened 2021-07-19 06:55 UTC by nisha331

### Description

A webapp that converts text to speech

### Checklist

- [ ] I've been assigned an issue related to this PR.
- [ ] I've used beautifiers.
- [ ] I've added my Project's name and description to `Index.md`
- [ ] I've made a README.md file for my Project.
## Related Issues or Pull Requests number

#229

2021-07-19 15:36 UTC, harshita2216 requested changes

2021-07-19 15:36 UTC, harshita2216 commented on text to speech/README.md
> +
Add screenshots please!

2021-07-20 08:09 UTC, harshita2216 approved these changes

2021-07-20 08:10 UTC, merged

2021-07-20 08:13 UTC, nisha331 commented
Thanks @harshita2216