my Online meal website added.
Ayushparikh-code/Web-dev-mini-projects pull request #330
Opened 2021-07-31 06:04 UTC by jugeshraghav

### Description

(Describe your project over here.)

### Checklist

- [ ] I've been assigned an issue related to this PR.
- [ ] I've used beautifiers.
- [ ] I've added my Project's name and description to `Index.md`
- [ ] I've made a README.md file for my Project.
- [ ] The README.md file of my projrct contains Project title, Description, Use of project, Set up, Stack used and Output (Screenshots). 

## Related Issues or Pull Requests number

(Write your answer here.)

2021-07-31 21:00 UTC, harshita2216 requested changes

2021-07-31 21:00 UTC, harshita2216 commented on Index.md
> +|[My Online Meal](https://github.com/abhishektyagi2912/Web-dev-mini-projects/tree/main/My-Online-Meal)| It is a simple and responsive website.
You've repeated the same mistake again of copying the previous link and not editing correctly.

2021-08-01 18:31 UTC, jugeshraghav commented
I have changed the path . Kindly check it once @harshita2216

2021-08-01 21:56 UTC, harshita2216 approved these changes

2021-08-01 21:57 UTC, merged